# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tsir <- function(rcpp_model_params, rcpp_init, rcpp_t0, rcpp_tmax, rcpp_seed, rcpp_verbose, rcpp_threads, rcpp_summary) {
    .Call('dynmod_tsir', PACKAGE = 'dynmod', rcpp_model_params, rcpp_init, rcpp_t0, rcpp_tmax, rcpp_seed, rcpp_verbose, rcpp_threads, rcpp_summary)
}

